baseURL = 'https://my-hugo-blog-psi.vercel.app/'
title = 'detem123 | 具身智能笔记'
theme = 'PaperMod'

[params.homeInfoParams]
  title = "Hi，我是 detem123 👋"
  content = "本科AI · 硕士空天机械 · 具身智能方向"

[params]
  socialIcons = [
    { name = "github", url = "https://github.com/detem123" }
  ]
  ShowReadingTime = true
  ShowWordCount = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 10
[[menu.main]]
  name = "归档"
  url = "/archives"
  weight = 20
[[menu.main]]
  name = "标签"
  url = "/tags"
  weight = 30
[[menu.main]]
  name = "关于"
  url = "/about"
  weight = 40
