baseURL = 'https://my-hugo-blog-psi.vercel.app/'
languageCode = 'zh-CN'
title = 'detem123 | 具身智能笔记'
theme = 'PaperMod'

[params]
  author = "detem123"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowWordCount = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowToc = true
  TocOpen = true

  customCSS = ["css/custom.css"]

  socialIcons = [
    { name = "github", url = "https://github.com/detem123" }
  ]

  [params.homeInfoParams]
    title = "Hi，我是 detem123 👋"
    content = "本科AI · 硕士空天机械 · 具身智能方向"

  [params.fuseOpts]
    isCaseSensitive = false
    shouldSort = true
    threshold = 0.4
    minMatchCharLength = 0
    keys = ["title", "permalink", "summary", "content"]

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 10
[[menu.main]]
  name = "归档"
  url = "/archives"
  weight = 20
[[menu.main]]
  name = "标签"
  url = "/tags"
  weight = 30
[[menu.main]]
  name = "搜索"
  url = "/search"
  weight = 40
[[menu.main]]
  name = "友链"
  url = "/links"
  weight = 60
[[menu.main]]
  name = "关于"
  url = "/about"
  weight = 50

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
